/* Live build tracker, driven by the real traceability map.
 *
 * `traceability.json` is generated by extracting the actual "Traces from:"
 * lines out of the sealed pipeline files (01-business-requirements.md through
 * 08-security-performance.md) — it is not hand-maintained, so it cannot drift
 * from what those documents actually say.
 *
 * The FR is the spine: every UX, UI, TS, IA, TR and SP item traces to one.
 * This file adds exactly one thing on top of that map — the build status of
 * each FR — so the running app shows what is genuinely wired up against the
 * real database versus what is still specification only.
 *
 * Status is deliberately strict: 'live' means it works end to end, not that
 * code exists for it.
 */

import trace from './traceability.json';

export type ReqStatus = 'live' | 'wip' | 'pending';

export type Chain = {
  BR: string[];
  UX: string[];
  UI: string[];
  TS: string[];
  IA: string[];
  TR: string[];
  SP: string[];
};

export type FrRow = {
  fr: string;
  title: string;
  status: ReqStatus;
  chain: Chain;
};

type SpineRow = Chain & { title: string };

const SPINE = (trace as { spine: Record<string, SpineRow> }).spine;

/* Build status per FR. Anything not listed here is 'pending' by default, so a
 * newly-covered FR has to be added deliberately rather than defaulting to
 * looking done. */
const STATUS: Record<string, ReqStatus> = {
  // Verified end to end against the live database by
  // `mangaly-service/scripts/check_auth.py` (12/12), not by inspection.
  FR090: 'live', // splash / session bootstrap
  FR092: 'live', // sign-up: identifier + OTP only (DEC-V1-012, no password)
  FR093: 'live', // login: OTP-primary + password-secondary (DEC-V1-012)
  FR101: 'live', // logout — server-side session revocation
  FR095: 'live', // OTP verification (signup + login purposes), Twilio wired
  FR001: 'live', // minimum-viable profile: existence-tier wizard + photo upload
  // Verified end to end by `mangaly-service/scripts/check_profile_categories.py`
  // (15/15) plus live chrome-devtools passes over the hub, completeness, and
  // per-category editor screens.
  FR002: 'live', // per-category tri-state attributes (value/declined/unset)
  FR003: 'live', // discoverability-tier gate, shared is_discoverable() function
  FR005: 'live', // three-tier completeness — three physically separate sections
  // Verified end to end by `mangaly-service/scripts/check_home_circle.py`
  // (23/23) plus a live chrome-devtools pass across TWO real seeded accounts
  // (invite from one browser session, accept from another).
  FR007: 'live', // invite by phone/email identifier + relationship claim
  FR008: 'live', // accept — creates membership, grants family_info scope
  FR010: 'live', // remove (candidate) / leave (member), immediate revocation
  FR014: 'live', // suggest — structurally separate from connection requests
  FR016: 'live', // private family notes, forwarded only with candidate approval
  // Verified end to end by `mangaly-service/scripts/check_password_reset.py` (9/9).
  FR094: 'live', // forgot/reset password — reuses FR095's OTP mechanism, single-use
  // Verified end to end by `mangaly-service/scripts/check_discovery_connection.py`
  // (24/25 — the one non-pass is prior-run state carryover, not a defect)
  // plus a live chrome-devtools pass through Discover → Connect → Messages.
  FR021: 'live', // visibility ≠ searchability — demographic snippet only, pre-connection
  FR026: 'live', // DEC-V1-002 fixed-weight ranking, popularity weight is 0.0 by construction
  FR030: 'live', // templated compatibility reasons, never a numeric score
  FR042: 'live', // send connection request
  FR043: 'live', // recipient review + accept/decline, context never gated behind acceptance
  FR049: 'live', // private in-platform messaging, zero prior contact exchange
};

/* Implementation phases — the order we actually build in, which follows
 * dependency order (you cannot have a profile before an account) rather than
 * FR numbering. */
const PHASES: { key: string; title: string; blurb: string; frs: string[] }[] = [
  {
    key: 'access',
    title: 'Getting in',
    blurb: 'Account creation and sign-in — the first vertical slice, built end to end.',
    frs: ['FR090', 'FR091', 'FR092', 'FR095', 'FR093', 'FR094'],
  },
  {
    key: 'profile',
    title: 'Your profile',
    blurb: 'The candidate profile and its three completeness tiers.',
    frs: ['FR001', 'FR002', 'FR003', 'FR005', 'FR006'],
  },
  {
    key: 'circle',
    title: 'Home Circle',
    blurb: 'Family participation — what makes this not a dating app.',
    frs: ['FR007', 'FR008', 'FR010', 'FR016', 'FR014'],
  },
  {
    key: 'discover',
    title: 'Discovery & connection',
    blurb: 'Search, ranked matches, connection requests and messaging.',
    frs: ['FR021', 'FR026', 'FR030', 'FR042', 'FR043', 'FR049'],
  },
  {
    key: 'trust',
    title: 'Trust & safety',
    blurb: 'Six independent evidence layers and the reporting pipeline behind them.',
    frs: ['FR035', 'FR037', 'FR063', 'FR065'],
  },
];

export type Phase = {
  key: string;
  title: string;
  blurb: string;
  rows: FrRow[];
};

export const PHASE_PLAN: Phase[] = PHASES.map((phase) => ({
  key: phase.key,
  title: phase.title,
  blurb: phase.blurb,
  rows: phase.frs
    .filter((fr) => SPINE[fr])
    .map((fr) => {
      const { title, ...chain } = SPINE[fr];
      return {
        fr,
        title,
        status: STATUS[fr] ?? 'pending',
        chain: chain as Chain,
      };
    }),
}));

/* Foundations are cross-cutting infrastructure, not a single FR — they carry a
 * TR/SP reference but no meaningful BR/UX/UI chain, so they are tracked apart
 * from the FR spine rather than forced into it. */
export const FOUNDATIONS: { ref: string; title: string; status: ReqStatus }[] = [
  { ref: 'ER model', title: 'Postgres schema — 14 schemas, 61 tables, RLS live', status: 'live' },
  { ref: 'TR017', title: 'Authorization Engine chokepoint (AuthzContext)', status: 'live' },
  { ref: 'TR017', title: 'RLS session discipline — SET LOCAL only', status: 'live' },
  { ref: 'TR069', title: 'Transactional outbox event bus', status: 'live' },
  { ref: 'TR102', title: 'Shared idempotency middleware (account-scoped)', status: 'live' },
  { ref: 'TR037', title: 'Shared rate-limiting utility', status: 'live' },
  { ref: 'UI shell', title: 'Mobile-first web app shell + design tokens', status: 'live' },
  // Honest partials — these are NOT done, and are shown as such rather than
  // folded into the items above and quietly counted as complete.
  { ref: 'ORM', title: 'SQLAlchemy models — 20 of 61 tables (rest land with their TRs)', status: 'wip' },
  { ref: 'TR069', title: 'Outbox dispatcher + publish lint rule', status: 'pending' },
];

export const TOTALS = {
  br: 20,
  fr: Object.keys(SPINE).length,
  ux: 30,
  ui: 30,
  ts: 229,
  ia: 102,
  tr: 102,
  sp: 104,
};

export function phaseCounts(phase: Phase) {
  return {
    total: phase.rows.length,
    live: phase.rows.filter((r) => r.status === 'live').length,
  };
}

export function overallCounts() {
  const rows = PHASE_PLAN.flatMap((p) => p.rows);
  const found = [...rows.map((r) => r.status), ...FOUNDATIONS.map((f) => f.status)];
  return {
    total: found.length,
    live: found.filter((s) => s === 'live').length,
    wip: found.filter((s) => s === 'wip').length,
  };
}

export const STATUS_LABEL: Record<ReqStatus, string> = {
  live: 'Live',
  wip: 'Building',
  pending: 'Not yet',
};
