#!/usr/bin/env bash
# =============================================================================
# ForKhatri — generate deploy/secrets/.env.production from the owner's inputs.
#
#   deploy/scripts/generate-secrets.sh              # create, or refresh inputs and keep existing secrets
#   deploy/scripts/generate-secrets.sh --rotate     # also generate new secrets (see README "Rotating secrets")
#   deploy/scripts/generate-secrets.sh --local-test # write deploy/secrets/.env.local-test for the local http rehearsal
#
# Reads deploy/secrets/owner-inputs.env (keys listed in owner-inputs.env.example).
# Runs in Git Bash on Windows, and on Linux/macOS. Prints key names only, never values.
# =============================================================================
set -euo pipefail

DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS_DIR="$DEPLOY_DIR/secrets"
INPUTS="$SECRETS_DIR/owner-inputs.env"
MODE=production
ROTATE=false
for arg in "$@"; do
  case "$arg" in
    --rotate) ROTATE=true ;;
    --local-test) MODE=local-test ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; exit 2 ;;
  esac
done

REQUIRED_INPUTS=(DOMAIN CLOUDFLARE_TUNNEL_TOKEN RESEND_API_KEY EMAIL_FROM SERVER_IP SERVER_USER)
R2_INPUTS=(R2_ACCOUNT_ID R2_ACCESS_KEY_ID R2_SECRET_ACCESS_KEY R2_BUCKET)
GENERATED=(POSTGRES_PASSWORD IDENTITY_OWNER_PASSWORD IDENTITY_APP_PASSWORD MANGALY_OWNER_PASSWORD MANGALY_APP_PASSWORD
           MILAVN_OWNER_PASSWORD MILAVN_APP_PASSWORD OTP_PEPPER MANGALY_SERVICE_KEY MILAVN_SERVICE_KEY)

declare -A IN=() OLD=()

# Parse KEY=VALUE files without executing them (tokens may contain shell metacharacters).
read_env_file() {
  local file="$1" target="$2" line key value
  while IFS= read -r line || [ -n "$line" ]; do
    line="${line%$'\r'}"
    [[ "$line" =~ ^[[:space:]]*(#|$) ]] && continue
    [[ "$line" == *=* ]] || continue
    key="${line%%=*}"; key="${key//[[:space:]]/}"
    value="${line#*=}"
    value="${value#"${value%%[![:space:]]*}"}"; value="${value%"${value##*[![:space:]]}"}"
    if [[ "$value" == \'*\' || "$value" == \"*\" ]]; then value="${value:1:${#value}-2}"; fi
    [[ "$key" =~ ^[A-Z0-9_]+$ ]] || continue
    if [ "$target" = IN ]; then IN["$key"]="$value"; else OLD["$key"]="$value"; fi
  done < "$file"
}

random_hex() { # 32 random bytes as 64 hex characters (URL- and shell-safe)
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 32
  else od -An -N32 -tx1 /dev/urandom | tr -d ' \n'; fi
}

if [ "$MODE" = production ]; then
  if [ ! -f "$INPUTS" ]; then
    echo "Missing $INPUTS" >&2
    echo "Copy deploy/secrets/owner-inputs.env.example to deploy/secrets/owner-inputs.env and fill it in." >&2
    exit 1
  fi
  read_env_file "$INPUTS" IN
  missing=()
  for key in "${REQUIRED_INPUTS[@]}"; do [ -n "${IN[$key]:-}" ] || missing+=("$key"); done
  if [ ${#missing[@]} -gt 0 ]; then
    echo "deploy/secrets/owner-inputs.env is missing a value for: ${missing[*]}" >&2
    exit 1
  fi
  r2_set=0; r2_missing=()
  for key in "${R2_INPUTS[@]}"; do if [ -n "${IN[$key]:-}" ]; then r2_set=$((r2_set+1)); else r2_missing+=("$key"); fi; done
  if [ "$r2_set" -gt 0 ] && [ "$r2_set" -lt ${#R2_INPUTS[@]} ]; then
    echo "Off-server backups need all four R2 keys; missing: ${r2_missing[*]}" >&2
    exit 1
  fi
  if [[ ! "${IN[DOMAIN]}" =~ ^[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?$ ]] || [[ "${IN[DOMAIN]}" != *.* ]]; then
    echo "DOMAIN must be a bare host name such as forkhatri.in (no https://, no path)." >&2
    exit 1
  fi
  [[ "${IN[EMAIL_FROM]}" == *@*.* ]] || { echo "EMAIL_FROM must contain an address on your verified domain." >&2; exit 1; }
  OUT="$SECRETS_DIR/.env.production"
  public_origin="https://${IN[DOMAIN]}"; scheme=https
  cookie_name='__Host-fk_session'; cookie_secure=true; local_http=false; email_provider=resend
else
  OUT="$SECRETS_DIR/.env.local-test"
  IN[DOMAIN]="localhost:${LOCAL_PORT:-8080}"
  IN[CLOUDFLARE_TUNNEL_TOKEN]=""; IN[RESEND_API_KEY]=""; IN[EMAIL_FROM]=""
  public_origin="http://${IN[DOMAIN]}"; scheme=http
  cookie_name='fk_session'; cookie_secure=false; local_http=true; email_provider=disabled
fi

for key in "${!IN[@]}"; do
  case "${IN[$key]}" in *"'"*|*$'\n'*) echo "$key contains a quote or newline, which is not supported." >&2; exit 1 ;; esac
done

[ -f "$OUT" ] && read_env_file "$OUT" OLD
declare -A SECRET=()
reused=0; created=0
for key in "${GENERATED[@]}"; do
  if [ "$ROTATE" = false ] && [ -n "${OLD[$key]:-}" ] && [[ "${OLD[$key]}" != *CHANGE_ME* ]]; then
    SECRET[$key]="${OLD[$key]}"; reused=$((reused+1))
  else
    SECRET[$key]="$(random_hex)"; created=$((created+1))
  fi
done

mkdir -p "$SECRETS_DIR"
umask 077
tmp="$(mktemp "$SECRETS_DIR/.env.tmp.XXXXXX")"
{
  echo "# Generated by deploy/scripts/generate-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Do not commit. Mode: $MODE."
  echo "DOMAIN='${IN[DOMAIN]}'"
  echo "PUBLIC_ORIGIN='$public_origin'"
  echo "PUBLIC_SCHEME='$scheme'"
  echo "CLOUDFLARE_TUNNEL_TOKEN='${IN[CLOUDFLARE_TUNNEL_TOKEN]}'"
  echo "RESEND_API_KEY='${IN[RESEND_API_KEY]}'"
  echo "EMAIL_FROM='${IN[EMAIL_FROM]}'"
  for key in "${R2_INPUTS[@]}"; do echo "$key='${IN[$key]:-}'"; done
  echo "SESSION_COOKIE_NAME='$cookie_name'"
  echo "SESSION_COOKIE_SECURE='$cookie_secure'"
  echo "LOCAL_HTTP_TEST='$local_http'"
  echo "SMS_PROVIDER='disabled'"
  echo "EMAIL_PROVIDER='$email_provider'"
  for key in "${GENERATED[@]}"; do echo "$key='${SECRET[$key]}'"; done
  echo "COMPOSE_PROJECT_NAME='forkhatri'"
  echo "RELEASE_ID='${OLD[RELEASE_ID]:-manual}'"
  echo "BACKUP_KEEP_DAYS='${OLD[BACKUP_KEEP_DAYS]:-14}'"
  echo "POSTGRES_IMAGE='${OLD[POSTGRES_IMAGE]:-postgres:18-bookworm}'"
  echo "CADDY_IMAGE='${OLD[CADDY_IMAGE]:-caddy:2.11-alpine}'"
  echo "CLOUDFLARED_IMAGE='${OLD[CLOUDFLARED_IMAGE]:-cloudflare/cloudflared:latest}'"
} > "$tmp"
chmod 600 "$tmp"
mv -f "$tmp" "$OUT"

echo "Wrote ${OUT#"$DEPLOY_DIR/"} (mode 600): ${#GENERATED[@]} secrets (${created} new, ${reused} kept)."
[ "$MODE" = production ] && [ "${r2_set:-0}" -eq 0 ] && echo "WARNING: R2 keys are empty, so backups will stay only on the VM. Strongly recommended: fill R2_* (deploy/README.md)."
[ "$ROTATE" = true ] && echo "Rotated. Run a deploy so migrations re-sync database passwords and services restart with the new keys."
exit 0
