-- =============================================================================
-- 003 — Allow the pre-authentication signup INSERT into mangaly_identity.account.
--
-- WHY (Step 9 Implementation finding, 2026-09-13, found by running the real
-- signup path against the live database rather than by reading the DDL):
-- 001-initial.sql created `account_self_only` as a FOR ALL policy with a USING
-- clause and no WITH CHECK:
--
--   CREATE POLICY account_self_only ON mangaly_identity.account
--     USING (id = NULLIF(current_setting('mangaly.account_id', true), '')::uuid);
--
-- Postgres uses a policy's USING expression as its WITH CHECK expression when no
-- WITH CHECK is given. For INSERT that is unsatisfiable at signup by
-- construction: the row's `id` is generated by the INSERT itself, and
-- `mangaly.account_id` is necessarily unset because the caller has no account
-- yet. Verified live as `mangaly_app`:
--
--   BEGIN; INSERT INTO mangaly_identity.account (phone_identifier, credential_hash)
--          VALUES ('+919999000001','x');
--   ERROR:  new row violates row-level security policy for table "account"
--
-- So TR092's `POST /auth/signup` could not create an account at all — a total
-- functional block on the module's first flow, not a hardening nit.
--
-- The three sibling tables (otp_challenge, password_reset_token, session) are
-- NOT affected and are deliberately left untouched: their policies key on
-- `account_id`, which the Identity Bridge resolves server-side and sets via
-- SET LOCAL before inserting. Confirmed live that all three insert successfully
-- under that context. Only `account` has the chicken-and-egg problem.
--
-- FIX: one additional permissive policy, INSERT only, on `account` only.
-- Permissive policies OR together, and for INSERT only WITH CHECK expressions
-- apply, so this opens the insert path without touching the self-only read
-- path `account_self_only` still enforces for SELECT/UPDATE/DELETE.
--
-- WHY `WITH CHECK (true)` IS THE RIGHT PREDICATE HERE, not a weaker fallback:
--   * Creating an account row is inherently a pre-authentication act. There is
--     no session context to constrain it against — any predicate referencing
--     `mangaly.account_id` is either unsatisfiable (the bug above) or trivially
--     forgeable by whatever the app already sets.
--   * An INSERT discloses nothing. `account_self_only` continues to restrict
--     every read, so a row created here is still invisible to everyone except
--     its own owner.
--   * The abuse this does permit — mass automated account creation — is a
--     denial-of-service concern, and SP092's denial-of-service row already
--     assigns it to the shared rate limiter (RateLimit-CC via SP037) plus OTP
--     gating, which is the correct layer for it. RLS is not a rate limiter.
--   * This is the same split-policy shape Step 7a's own live-verification pass
--     already applied to the 11 `outbox_event` tables (`FOR INSERT WITH CHECK
--     (true)` + a restricted read policy), so it follows an existing precedent
--     in this schema set rather than introducing a new pattern.
--
-- Idempotent and safe to re-run.
-- =============================================================================

DROP POLICY IF EXISTS account_signup_insert ON mangaly_identity.account;
CREATE POLICY account_signup_insert ON mangaly_identity.account
  FOR INSERT
  WITH CHECK (true);

COMMENT ON POLICY account_signup_insert ON mangaly_identity.account IS
  '[TR092/Step 9] Signup is pre-authentication: no session variable exists to constrain the INSERT against, and the row''s own id does not exist until the INSERT runs. Reads stay self-only via account_self_only; mass-registration abuse is handled by the shared rate limiter (SP037/SP092), not by RLS.';
